version: '3'

services:
    mysql8:
        image: mysql:8.0
        container_name: mysql8
        env_file: ./mysql/8.0/.env
        ports:
            - "3308:3306"
        volumes:
            - ./mysql/8.0/lib:/var/lib/mysql

    mysql57:
        image: mysql:5.7
        container_name: mysql57
        env_file: ./mysql/5.7/.env
        ports:
            - "3307:3306"
        volumes:
            - ./mysql/5.7/conf.d:/etc/mysql/conf.d
            - ./mysql/5.7/lib:/var/lib/mysql

    mysql55:
        image: mysql:5.5
        container_name: mysql55
        env_file: ./mysql/5.5/.env
        ports:
            - "3355:3306"
        volumes:
            - ./mysql/5.5/conf.d:/etc/mysql/conf.d
            - ./mysql/5.5/lib:/var/lib/mysql

    mariadb10_7:
        image: mariadb:10.7
        container_name: mariadb10_7
        env_file: ./mariadb/10.7/.env
        ports:
            - "3357:3306"
        volumes:
            - ./mariadb/10.7/conf.d:/etc/mariadb/conf.d
            - ./mariadb/10.7/lib:/var/lib/mariadb

    mariadb10_3:
        image: mariadb:10.3
        container_name: mariadb10_3
        env_file: ./mariadb/10.3/.env
        ports:
            - "3356:3306"
        volumes:
            - ./mariadb/10.3/conf.d:/etc/mariadb/conf.d
            - ./mariadb/10.3/lib:/var/lib/mariadb

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            - "PMA_ABSOLUTE_URI=http://www.pma.test"
            - "VIRTUAL_HOST=www.pma.test"
            - "PMA_HOSTS=mysql8,mysql57,mysql55,mariadb10_7,mariadb10_3"
        ports:
            - 8888:80
        restart: always

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
            - 1025:1025
            - 8025:8025

    minio:
        command: server /data --console-address ":9001"
        container_name: minio
        image: minio/minio
        env_file: ./minio/.env
        volumes:
            - ./minio/data:/data
        ports:
            - 9000:9000
            - 9001:9001

networks:
    default:
        external:
            name: local_default
